### ISSUE TITLE
optixModuleCreateFromPTX failed with code 7001

### ISSUE THREAD

**Issue by knightcrawler25** [owl-project/owl#108]
Hi,

I was trying out the voxrender sample and when I try to run it I get the following error:

```
Optix call (optixModuleCreateFromPTX(device->optixContext, &device->moduleCompileOptions, 
&device->pipelineCompileOptions, parent->ptxCode.c_str(), strlen(parent->ptxCode.c_str()), log, 
&sizeof_log, &module )) failed with code 7001
```
The other samples work fine.

I'm on CUDA 10.2 and OptiX 7.2
GPU: GTX 750Ti (Maybe the reason for the issue?)

Here is the output incase it helps: [log.txt](https://github.com/owl-project/owl/files/6976538/log.txt)

**Comment by knightcrawler25** [comment]
Update:

The voxrender sample works after commenting out this line:
https://github.com/owl-project/owl/blob/d3abbbf70619650fbe0527b7a38aeb281130ebd8/samples/advanced/rtgems2-voxrender/deviceCode.cu#L82

However, I'm not sure what's causing the issue

**Comment by dylanlacewell** [comment]
Hi, thanks for posting the full log, this is helpful.  You appear to be hitting a bug with OptiX that we just found out about ourselves recently.  It happens when using "bound" launch param values, which is a way of telling OptiX that even though you have the value as a launch param, it is really a constant and can be compiled as such.

The most expedient workaround (assuming you still want clipping to work), is to comment out this piece of code in hostCode.cpp near line 1143 and rebuild:

```
#if 0   // disable as workaround

  // Tell OptiX which launch params will be constant across all frames with given values, so 
  // they can be specialized if possible during module compile.
  OWLBoundValueDecl boundValues[] = {
    { launchVars[0], &this->enableToonOutline},
    { launchVars[1], &this->enableClipping},
    { }
  };
  owlContextSetBoundLaunchParamValues(context, boundValues, -1);
#endif
```

Commenting this out will make the values go back to being actual runtime values instead of constants, so maybe just a tiny bit of perf loss, but it should also work around the OptiX bug.  You could also replace these params with regular #define constants if you wanted to, but that's more effort.

The OptiX bug should be fixed in an upcoming driver release according to the developers.  If you can confirm the workaround then I'll do something similar and check it in as a temp fix.

**Comment by dylanlacewell** [comment]
Btw, I'm happy to hear this runs on a GTX 750 Ti!  I only tested as far back as Pascal when developing the sample.  I would guess passing "--scenetype user" is a good option for this GPU since it will use the least memory and might even be the fastest kernel.

**Comment by knightcrawler25** [comment]
I just tested the workaround you suggested and can confirm that it works :) 

I also tried loading up all the scene*.vox files from Metro Minis and I get the best performance with 'user' layout and slightly worse perf with 'userblocks' whereas 'flat' and 'instanced' run out of memory on this 2GB card. To be honest, it's surprising that the sample even works on this GPU :D

Thanks a lot for your help in getting this to run :)

**Comment by dylanlacewell** [comment]
Merged the workaround, closing. 
Future work: re-enable bound values (in a couple months?) when the driver bug is fixed
