### ISSUE TITLE
Copy DeviceBuffer back to Host 

### ISSUE THREAD

**Issue by vani-nag** [owl-project/owl#111]
Since owlBufferGetPointer() only works with ManagedMemory and HostPinned buffers, is there a method that allows us to copy modified DeviceBuffers from device to host? If not, is there a way I can implement it myself?

**Comment by szellmann** [comment]
afaik `owlBufferGetPointer()` returns a _device_ pointer, so sth. like `cudaMemcpy(hostPtr, owlBufferGetPointer(deviceBuffer, deviceID), numBytes, cudaMemcpyDeviceToHost);` should always work.

I suppose a function like `owlBufferDownload()` is intentially not part of the API b/c that would require the lib to implement some sort of multi GPU gather (and in the case of single device only would literally be the same as the `cudaMemcpy` from above, but with a slightly different interface).

**Comment by ingowald** [comment]
Just to elaborate a tiny bit on this: Due to OWL's built-in multi-device support any device buffer you create through the API will actually end up creating one device buffer on each GPU that you created the context over; with possibly a different address on each GPU, and with possibly different data that your program may have written into it. Thus, asking to downtoad "the" buffer only makes sense if you were to say which GPU's version of the buffer you want to download (and "gathering" from multiple devices wouldn't make sense, either, since it's not one buffer "split" across multiple devices, but really one complete buffer per device).

That said, it would make total sense to have a owlBufferDownload(hostPtr,buffer, deviceID) (at least for buffers of scalar types). Internally this would however do exactly what stefan just suggested: a cudaMemcpy from owlBufferGetPointer() to the host pointer so this is what I'd suggest to use for now. If a owlBufferDownload would significantly help we can add this, though - it would make sense.

**Comment by vani-nag** [comment]
Thank you for your responses @ingowald @szellmann !
Your answers worked well for me.
I was trying out the different buffers available and found that using ManagedMemory buffers gave better performance compared to HostPinned buffers. I wanted to see if using a DeviceBuffer would further improve performance.

**Comment by ingowald** [comment]
Ah, makes sense. If you're running in multi-gpu mode you might get better perf w/ device buffers, but then you'll have to deal with a few other issues as well (like how to merge different GPUs' pixels back into one image); other than that managed mem will likely by just as good as device buffers. Closing this and adding a new feature request for owlBufferDownload() function to get a more meaningful issue name. 
keep us in the loop! :-)
