### ISSUE TITLE
Calculate device execution time

### ISSUE THREAD

**Issue by vani-nag** [owl-project/owl#127]
I'm unsure of how to calculate the device execution time i.e., execution time _after_ data has been copied to the device and _before_ data has been copied back to the host. 
This should include BVH build+traversal, rayGen, IS etc..
I currently have timers at the start and end of owlLaunch2D() and owlGroupBuildAccel(). Is this the right approach?

**Comment by ingowald** [comment]
yes, that sounds right. OWL is intentionally a very "thin" abstraction layer, and will _not_ do any delayed copying, caching, etc; so any uploads should already have happened in buffer creation/buffer upload; all buiding should have happened exactly within owlGroupBuildAccel, etc - so the launch really is just the launch. Also, the default owlLaunch2D is synchronous, so that function won't return until the launch is completed.

**Comment by ingowald** [comment]
closing this since it's not a "issue" that needs solving. Looking into enabling github 'discussions' to discuss questions like that.
