### ISSUE TITLE
modern cmake: issues encountered while switching from legacy cmake

### ISSUE THREAD

**Issue by LivelyLiz** [owl-project/owl#136]
I had some issues switching to the new modern cmake variant of the project. I'll just write it down here in case someone has the same issues. Maybe some of this can be added to the README or changed in the CMakeLists.txt

**Project setup**
I use CPM to download the dependencies. That's why owl's source is located in the build directory. My (simplified) project structure looks like this:
```
project
|- build
|--- _deps
|----- owl-src
|- deps
|--- CMakeLists.txt   <- this is where owl gets included as subdirectory
|- app
|--- deviceCode.cu
|--- hostCode.cpp
|--- hostCode.h
|--- app.cpp
|--- CMakeLists.txt
|- CMakeLists.txt
```
Edit: I currently use cmake version 3.16.3.

**Issues**

- `embed_ptx.cmake and run_bin2c.cmake must be on CMAKE_MODULE_PATH` from `embed_ptx.cmake` (line 34)
\
This was the one that was puzzeling me the most. Right before adding owl with `add_subdirectory` I was calling `list(APPEND CMAKE_MODULE_PATH "${Owl_SOURCE_DIR}/owl/cmake/" "${OptiX_INSTALL_DIR}")` but inside `embed_ptx.cmake` owl's source directory wasn't present in the `CMAKE_MODULE_PATH`. The reason was the directory wasn't added in the project's root CMakeLists but the one in the `deps` directory. The solution was to export this to the parent scope, i.e. calling `set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}" PARENT_SCOPE)` after `list(APPEND ...)`

- OptiX wasn't found although `OptiX_INSTALL_DIR` was set
\
Before the switch, I set the OptiX install directory via command line argument `-DOptix_INSTALL_DIR=...` but this didn't work anymore. My solution was to modify the `FindOptiX.cmake` to also check for the CMake Variable and not only the environment variable. The simpler solution would probably be to just set the environment variable instead.
  ```
  if (DEFINED ENV{OptiX_INSTALL_DIR})
    message(STATUS "Detected the OptiX_INSTALL_DIR env variable (pointing to $ENV{OptiX_INSTALL_DIR}; going to use this for finding optix.h")
    find_path(OptiX_ROOT_DIR NAMES include/optix.h PATHS $ENV{OptiX_INSTALL_DIR})
  elseif (DEFINED OptiX_INSTALL_DIR)
    message(STATUS "Detected the OptiX_INSTALL_DIR variable (pointing to ${OptiX_INSTALL_DIR}; going to use this for finding optix.h")
    find_path(OptiX_ROOT_DIR NAMES include/optix.h PATHS ${OptiX_INSTALL_DIR})
  else()
    find_path(OptiX_ROOT_DIR NAMES include/optix.h)
  endif()
  ```

- changing `cuda_compile_and_embed` to `embed_ptx`
\
This was kinda obvious by looking into the new samples, however, it was not obvious that the device code file (aka the .cu file) has to match the name with the variable for the ptx code. As seen in the project structure, my file's name is `deviceCode.cu`. Previously, the variable for the ptx code was set as `extern "C" char ptxCode[];`. This gave me a `undefined reference to 'ptxCode'` linker error. The solution was to change the name of the variable to `extern "C" char deviceCode[];`.

- setting another alias name for owl
\
This is probably more of a personal preference problem. I wanted to rename the target `owl::owl` to `Owl` but this isn't possible because `owl::owl` is an alias target itself. I solved it by using the underlying target `owl`. I never had an issue renaming other libraries like Eigen or Ceres, so maybe it would be a good idea to call the actual target `owl::owl` and make `owl` an alias? No pressing matter, just a suggestion.

- Using owl types in a header now requires owl to be linked as PUBLIC in `target_link_libraries`
\
Again, probably a personal thing. I have a small library (similar thing to SampleRenderer in the advanced example) and a small test executable. I wrapped the legacy cmake owl in a target on my end and could add it as `PRIVATE` in target_link_libraries to the library. However, the only reason this worked was because my quick and dirty test executable was  in the same CMakeLists.txt as the library that uses owl, and for the library to compile one had to use `include_directories(${Owl_INCLUDES})`. So the owl and optix headers were implicitly added as include directories to the executable target. With the modern CMake, this  line is not needed anymore and my library has to explicitly expose owl as build dependency.

**Comment by ingowald** [comment]
first of all: thx for that feedback - we ran into way(!) more issues with the switch to modern cmake than we had expected; and though we've yesterday made good progress getting everything back to normal this feedback from an outside user - who even uses it in a different way than we do - is highly appreciated.

I'll let @jeffamstutz and @lpisha answer more on most of the above things  of the other things (they know more about cmake than I do); but two brief comments/questions:

- re the "extern C symbol is now the same as _the input .cu filename_, not a name chosen by the user any more: I stumbled over that as well, partly because it required changing every project (and more than jsut the cmakefiles), partly because I found "deviceCode" to be too meaningless a name. Two questions (for discussion) : a) is this something we'll just "get used to" and then not worry any more going forward? (ie, would somebody that never knew it any different still be annoyed by it?); and/or b should we instead extend this macro to provide a user-chosen name instead of the name of the cu file? Or at least, name the variable after the _target_ rather than after the input file?

- re alias: (disclaimer: i'm not an expert here): could you simply define a _new_ alias from owl::owl to Owl? (instead of from owl to Owl)?
- 
- re "couldn't find optix despite OptiX_INSTALL_DIR": can you verify that this is _still_ an issue even in latest release-1-1 brnach? (v1.1.3, i think). I did have that issue and did fix it on my side; just curious to see if that doesnt work in your usage pattern.

Anything else: @jeffamstutz ? @lpisha ?

**Comment by finartist** [comment]
> re alias: (disclaimer: i'm not an expert here): could you simply define a _new_ alias from owl::owl to Owl? (instead of from owl to Owl)?

No, this is not possible. CMake doesn't allow alias targets from alias targets. I probably didn't express myself well in my first post. With "rename" I meant introducing a new alias target from `owl::owl` (aka `add_library(Owl ALIAS owl::owl)`). This was only possible by using the original target `owl`. I think the recommendation for modern CMake is to provide exactly these alias targets. Weirdly enough, I can alias `Eigen3::Eigen` as Eigen although this is also an alias name ([see here](https://gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt#L584)). Maybe this has something to do with exported targets? I am not a CMake expert myself and never had to write something that will be used by other people \^\^"

> re "couldn't find optix despite OptiX_INSTALL_DIR": can you verify that this is _still_ an issue even in latest release-1-1 branch? (v1.1.3, i think). I did have that issue and did fix it on my side; just curious to see if that doesnt work in your usage pattern.

I was using the launch3d branch which seems to have the same FindOptiX.cmake as the release-1.1 branch. It only checks for environment variables, not CMake variables. That's why I tried with an additional `elseif (DEFINED OptiX_INSTALL_DIR)`, which checks for the CMake variable.

**Comment by finartist** [comment]
> I'm curious what is the goal with aliasing owl to something else? (Just want to learn what your preferences are, as that helps me grow my understanding of how people like to use CMake differently than me!)

@jeffamstutz I am just annoyed that about every dependency has different naming conventions for their targets (specifically capitalization). While Eigen uses `Eigen3::Eigen`, Ceres uses `Ceres::ceres` and Owl goes `owl::owl`. This is probably a non-issue for most people but I always forget how the correct target is spelled and have to look it up again, so I alias them to a name I know how to spell and capitalize correctly. Additionally, when you also have dependencies to libraries that do not export targets at all (like owl did), I just keep on with my own naming convention.

> One idea was to change `OUTPUT_TARGET` into a list of targets that `embed_ptx` would link the generated PTX target to. This would eliminate the need to specify a name of a target that you have to explicitly link yourself.

I like that idea. It seems less error prone to me. Also, I think it is fine that the ptx variable has to match the .cu filename, it should just me mentioned somewhere. To further emphasize the connection between the cu file and the ptx code, it might be better if the symbol has to be called <filename>_ptx. I would find it less confusing because then I doesn't look a random variable that is called like a file.

**Comment by jeffamstutz** [comment]
> To further emphasize the connection between the cu file and the ptx code, it might be better if the symbol has to be called _ptx

I like this! I'll see if I can get a PR up with this today for folks to look at.

**Comment by jeffamstutz** [comment]
@finartist would you be up for having a look at https://github.com/owl-project/owl/pull/137 to see if that positively address some of your feedback?

**Comment by finartist** [comment]
> @finartist would you be up for having a look at #137 to see if that positively impacts some of your feedback?

@jeffamstutz Looked at it, the embed_ptx problem isn't solved. The configure step went well but I got an error in the build (`CMake Error: Error processing file: /run_bin2c.cmake`). It is again a CMake variable scoping problem. The variable `EMBED_PTX_DIR` is empty when the function gets called.

Caching the path by changing `set(EMBED_PTX_DIR ${CMAKE_CURRENT_LIST_DIR})` to `set(EMBED_PTX_DIR ${CMAKE_CURRENT_LIST_DIR} CACHE INTERNAL "")` solved that.

> Edit 2: I am a bit more hesitant now to dive into the idea of linking to output targets directly. Without a stable, singular name to generate the embedded PTX target name, I'm not sure what the most robust option should be. (maybe a good solution will emerge later)

I think we can also just leave it as is then. The way it is now  feels more like adding a file/library to a target. I think this makes more sense than the other way which is more like adding a target to something. (Although, I can imagine that I would more often forget that I have to explicitly link it than writing the target into the call of the embed_ptx function.)

**Comment by finartist** [comment]
> Would it be clearer to rename it to something like `add_embedded_ptx()` and make the first argument always the target name? That would make it look closer to other bespoke target creation commands IMO.

Yeah, I think this would be better and make it clearer.
