### ISSUE TITLE
Possible to set breakpoint in __closesthit__radiance() ?

### ISSUE THREAD

**Issue by ForceConstant** [owl-project/owl#180]
Using cuda-gdb is it possible to set a breakpoint in __closesthit__radiance() ? I see that I can set debug in Impl.cpp before building programs, but can't figure the rest out?

**Comment by dylanlacewell** [comment]
The OptiX 7.5 release has some support for breakpoints, but I think they require that shaders are compiled to "OptiX-IR" instead of PTX.   See the release notes here: 

https://forums.developer.nvidia.com/t/optix-7-5-release/218032

OWL would probably need to be modified to support OptiX-IR as a shader build target via CMake.  Not implemented yet afaik.

You probably already know this, but the classic OptiX/OWL shader debugging method is to use printfs, but limited to one pixel, one ray, etc, using a conditional check of the launch index.  It sounds bad but can still work.
