### ISSUE TITLE
owlBufferUpload incorrect arg name

### ISSUE THREAD

**Issue by oceanusxiv** [owl-project/owl#183]
So currently, the function signature of `owlBufferUpload` is

```
OWL_API void 
owlBufferUpload(OWLBuffer buffer,
                const void *hostPtr,
                size_t offset OWL_IF_CPP(=0),
                size_t numBytes OWL_IF_CPP(=size_t(-1)));
```
with the description stating 
```
/*! uploads data from given host poiner to given device. offset refers
    to the offset (in bytes) on the device. \param numbytes is the
    number of bytes to upload; -1 meaning "full buffer" */
```

However, if you look at the implementation of  `owlBufferUpload`, in particular in,,
https://github.com/owl-project/owl/blob/68999445140b35beda9ce6450625075bdee5fdae/owl/impl.cpp#L846
you'd note that it calls into `Buffer::SP::upload`, which actually has a function signature of
https://github.com/owl-project/owl/blob/68999445140b35beda9ce6450625075bdee5fdae/owl/Buffer.cpp#L127
Note how it says `count`. Owl Buffers are type aware upon construction and the upload function explicitly multiplies the count by the type of the buffer. Given this implementation, I think the `owlBufferUpload` signature needs to be changed from `numBytes ` to `count` to accurately reflect the implementation and avoid misleading the user.

**Comment by ingowald** [comment]
Oooh, nice catch. I'll have to look into that a bit deeper because that "upload" function is also connected with some other stuff (like owlBufferCreate), but at first glance what you're saying sounds very true indeed. IIRC the reason for that is that "originally" buffers were untyped, and "owlUpload" was supposed to be a general cudaMemcpy; but then buffers become typed, and at some point later in time all the create() functions got simplified/unified by merging all their "initial upload" parts with that existing upload() function.... which probably made owlBufferUpload() implicitly typed even though initially it wasn't supposed to be. 

I'll have to think a bit about what the right solution is - if we simply update the docs to match what the function does then we dont' have a "totally-general" upload function any more .... though being types is most likely what users would expect, anyway, so in all likelihood that _is_ the right solution. But let me have a deeper look first. Either way: nice catch, thanks for reporting!

**Comment by ingowald** [comment]
BTW - since you seem interested in using that upload function - would we / should we then still have the 'offset' parameter? It'd have to be typed, too, at the least. Also, it _looks_ misleading that one could write 'owlBufferUpload(myArray,10)', and the 10 would default to _offset_, not _count_.

**Comment by oceanusxiv** [comment]
Oh yes now that you mention it the offset should probably be typed too, and reflected in the function signature and documentation.

As for typed/untyped upload. I think if there's a need for an untyped upload function, and there can be, it can be implemented as a separate, explicitly untyped upload function, with a different function name and function signature. This way the caller would know what they're getting into.
