### ISSUE TITLE
Cuda Surface objects possible?

### ISSUE THREAD

**Issue by deibich** [owl-project/owl#203]
Hey,

is it possible to use cuda Surface objects with owl?

https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__SURFACE__OBJECT.html#group__CUDART__SURFACE__OBJECT
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#surface-functions

**Comment by ingowald** [comment]
Just to follow up with some more details on what I meant with "raw" parameters for cuda texture objects:

The "easy" way of using textures in OWL is the following:

a) use a cudaTextureObject_t in your owl geom type

    struct MyGeom { cudaTextureObject_t tex; };

b) declare it as OWL_TEXTURE parameter on the host

    OWLParam myGeomParams[] = { ... { "tex", OWL_TEXTURE, ... } ... }

c) create a OWLTexture

   OWLTexture myTex = owlTexture2DCreate()

d) set this param

   owlGeomSetTexure(myGeom,"tex",myTex)

"under the hood", the owlTextureCreate will just do the regular cuda texture array and texture object creation, etc, and create some internal struct that stores, for each GPU, the resulting cudaTextureObject. The owlGeomSetTexture will then, for each device, get the proper cudaTextureObject_t, upload that to the respective gpu, and write that into that MyGeom struct's 'tex' field. In fact, the only reason this entire process exists is that if you have multiple GPUs you actually have to create a _different_ cudaTextureObject_t for each GPU - but the user won't want to see that, so the OWLTexture handles all that internally without the user even seeing it.

However, instead of all this higher-level wrapper stuff, you could _also_ have done the following:

a) use a cudaTextureObject_t in your geom struct, as above:
 
    struct MyGeom { cudaTextureObject_t tex; };

b) declare that as a _USER_ parameter on the host:

    OWLParam myGeomParams[] = { ... { "tex", OWL_USER_PARAM(cudaTextureObject_t, ... } ... }

this user param will just declare the offset and size, but _not_ semantically what it is. 

c) create your own CUDA texture using the plain old cuda calls:

   cudaTextureObject_t myTex; cudaTextureTextureObject(...) 

d) set this via a "raw" parameter call:

   owlGeomSetRaw(myGeom,"tex",&myTex)

(mind the "&" before the myTex!). What this does is just tell owl: hey, i told you there's a user param of that name, with that size and offset in the geom - and here's a pointer to whatever bytes I want to have copied into that, whereever you might want to put it in the SBT. Ie, OWL will then copy the number of bytes that tsize user type's size indicates from that pointer, copy them to the devce, and put them at the right address.

And yes, that'll work just fine - in fact it's exactly what you'd do in optix as well, except in optix you'd also have to do SBT construction, cudaMemcpy's to get it to the dvice, etc - and owl will still do all of that. For surace objects, i'd expect that to work exactly the same way, too. Can't say for sure that it works, but would expect so, please let me know if you play with it.

PS: One caveat is multi-device - if you need to have different values for each device then it'll get a bit more tricky. Send me an emai lif you ever go that far down the rabbit hole.

**Comment by deibich** [comment]
Thank you for your detailed explanation which helped me a lot to track down my error. Now I'm able to write to a cuda surface object. 

As a quick test I copied the sample `s01-simpleTriangles` and defined a `cudaSurfaceObject_t` in `RayGenData`.

I used glfw to quickly set up a offscreen context and registered the texture in cuda. Most of the code is from OWLViewer class and examples from stackoverflow or the cuda documentation

```C++
...

GLFWwindow* offscreen_context;
GLuint   fbTexture  {0};
cudaGraphicsResource_t cuDisplayTexture { 0 };
cudaSurfaceObject_t cuSurfaceObj { 0 };

...

glfwInit();
glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
offscreen_context = glfwCreateWindow(fbSize.x, fbSize.y, "", NULL, NULL);

glfwMakeContextCurrent(offscreen_context);
glGenTextures(1, &fbTexture);
glBindTexture(GL_TEXTURE_2D, fbTexture);
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, fbSize.x, fbSize.y, 0, GL_RGBA,
                          GL_UNSIGNED_BYTE, nullptr);

cudaGraphicsGLRegisterImage(&cuDisplayTexture, fbTexture, GL_TEXTURE_2D, 0);
cudaGraphicsMapResources(1, &cuDisplayTexture);

cudaArray_t arrayPtr;
cudaGraphicsSubResourceGetMappedArray(&arrayPtr, cuDisplayTexture, 0, 0);

cudaResourceDesc resDesc{};
memset(&resDesc, 0, sizeof(resDesc));
resDesc.resType = cudaResourceTypeArray;
resDesc.res.array.array = arrayPtr;
cudaCreateSurfaceObject(&cuSurfaceObj, &resDesc);

OWLVarDecl rayGenVars[] = {
    { "surf",          OWL_USER_TYPE(cudaSurfaceObject_t), OWL_OFFSETOF(RayGenData, surf)},
     ...
    {/* sentinel to mark end of list */ }
};

...

owlRayGenSetRaw   (rayGen, "surf", &cuSurfaceObj);

...


```

On the device side it's now possible to read and write the surface object
`surf2Dwrite(owl::make_rgba(color), self.surf, sizeof(uint32_t) * pixelID.x, pixelID.y);`
