### ISSUE TITLE
[Question] What's the right way to release GPU resource after `owlRayGenLaunch`?

### ISSUE THREAD

**Issue by MikeZhu92** [owl-project/owl#205]
Thank you for providing all the nice tutorials!
I've a question regarding gpu resource release.
I saw most of the sample code in `samples/cmdline` was doing this:
```
owlContextDestroy(context);
```
in the first sample we free the resource more explicitly by doing:
```
owlModuleRelease(module);
owlRayGenRelease(rayGen);
owlBufferRelease(frameBuffer);
owlContextDestroy(owl);
```

I'm wondering what is the right way to free resource.
In my toy sample, I see this error message if I only do `owlContextDestroy`:
```
#owl: #owl: context is dying; number of API handles (other than context itself) that have not yet been released (incl this context): 9
#owl:  - owl::APIContext
#owl:  - Module
#owl:  - TriangleGeomType
#owl:  - DeviceBuffer
#owl:  - DeviceBuffer
#owl:  - TrianglesGeom
#owl:  - TrianglesGeomGroup
#owl:  - InstanceGroup
#owl:  - RayGen
Segmentation fault (core dumped)
```
After calling 
```
owlModuleRelease
owlRayGenRelease
owlBufferRelease
owlGroupRelease
owlGeomRelease
owlContextDestroy
```
I'm able reduce it to 2:
```
#owl: #owl: context is dying; number of API handles (other than context itself) that have not yet been released (incl this context): 2
#owl:  - owl::APIContext
#owl:  - TriangleGeomType
Segmentation fault (core dumped)
```

Thank you so much for your help!

**Comment by ingowald** [comment]
Hm; interesting. Could you provide a reproducer? Long story short what you're describing sounds like a bug.

In long form: "In theory", resource management in OWL is that all objects live "within" a context, and inside that context shold be refcounted. Ie, if you "create" an object (say, a geom) you create it and get a "handle" for that object that has a refcount of 1; if you then _use_ that for soemthing (use it in a group, or add it as a paramter etc) the recount gets increased by 1, etc. If you later "release" an object it reduces the recount for that object, and if the recount is 0 it gets actually freed, otherwise it lives on until all other references have been released, etc. However, all objects live "within" the context that was used to create it, so if you destroy the parent _context_ it should immediately kill everything within - handles, internal data, etc. Basically, nothing should live or be allocated any more that was allocated within that context. 

One caveat: since destroying the context will also destroy all the objects and handles within that context none of the handles you used to create things are valid any more. Ie, a possible source of your core dump is that _maybe_ you're destroying that context, and then _after_ that are trying to release something that's then no longer valid.

**Comment by ingowald** [comment]
Oh, another possible bug is if you used an _async_ launch the launch mitght still be running before you do the context destroy - that could also cause a core dump. Either way i'd be happy to look into any reproducer to find and eliminate.
