### ISSUE TITLE
[Question]Why don't you use curand?

### ISSUE THREAD

**Issue by wangzilu** [owl-project/owl#206]
I would like to ask why owl don't use curand to generate random number? your own random number generator will more efficient than curand? thank you!

**Comment by ingowald** [comment]
No particular reason. IIRC when I wrote the first sample with random number I "stole" the random number generator from a corresponding OptiX 6 sample - and since that worked great it's simply been re-used and re-copied ever since. If curand is better, and you want to change (some of?) the samples to use that, then feel free to send a PR.

**Comment by wangzilu** [comment]
thanks a lot,I will try that.
