### ISSUE TITLE
Is there any method to parallel set transform matrix?

### ISSUE THREAD

**Issue by wangzilu** [owl-project/owl#209]
in the sample interactive/int11/rotating boxes, in render function, use a for loop to set transform matrix to instance group, is there any possible do this in a CUDA Kernel ? suppose we have ten or hundred millions boxes, will this serial for loop become a performance bottleneck?

**Comment by ingowald** [comment]
Yes, that would almost certainly be a performance bottleneck. In this case you're right that you'd want to set those transforms on the device, in a cuda kernel - but since nobody has asked for that yet this functionality doesn't exist ... yet. 

I've actually been waiting for somebody to ask for that (because it's easier to add a feature if somebody actually uses it and gives feedback), so happy to look into adding that. If you could, could you send me an email (ingowald at gmail) with some more info as to what you're trying to do? If I do add that feature then I just as well add it in the most useful form :-)

**Comment by ingowald** [comment]
I just had a quick look. It's a bit more of a change than just providing a gpu-side array of transforms - but it's doable. would still like an email discussion on what exactly you'd like to do - and whether my current plans for realizing it would work for your -  but overall it should be doable

**Comment by wangzilu** [comment]
@ingowald than you for your replying, I have sent you an email, looking forward to your discussion.

**Comment by wangzilu** [comment]
I have done this in InstanceGroup class by set dd.optixInstanceBuffer in a CUDA Kernel:)
