### ISSUE TITLE
How to ray trace a child Instance of IAS only?

### ISSUE THREAD

**Issue by wangzilu** [owl-project/owl#214]
Hello, in samples/cmdline/s06-mixedGeometries,
in host code, 
```
  OWLGroup world = owlInstanceGroupCreate(context,2);
  owlInstanceGroupSetChild(world,0,userGeomGroup);
  owlInstanceGroupSetChild(world,1,triangleGeomGroup);
```
it build a IAS and set two Childs, I would like to know, in device code, how could I trace only one of them.

I modified device code the tracePath function,
```
OptixTraversableHandle child1 = optixGetInstanceTraversableFromIAS(self.world, 1);

  OptixTraversableHandle child = optixGetInstanceChildFromHandle(self.world);
  /* iterative version of recursion, up to depth 50 */
  for (int depth=0;depth<50;depth++) {
    prd.out.scatterEvent = rayDidntHitAnything;
    owl::traceRay(/*accel to trace against*/child1,
                  /*the ray to trace*/ ray,
                  /*prd*/prd);
```
It dose not work.

**Comment by wangzilu** [comment]
I tried owlSetMask, thanks.

**Comment by ingowald** [comment]
wangzilu - i don't think that'll work. the pipeline is set up for instancing, so the trace call will expect a top-level bvh containing instances ... but the child one is a BLAS, so that won't work (the trace call would need to know not only the traversable handle, but also the SBT offset where that SBT starts).
the only thing i could think of is to create a second TLAS that only contains the second BLAS (this is very cheap, since that TLAS only has a single element), then use a numerical ID rather than 'getInstanceChildFromHandle'.
