### ISSUE TITLE
feature request: OWL_BUFFER_GROUP and OWL_TEXTURE_GROUP

### ISSUE THREAD

**Issue by n8vm** [owl-project/owl#56]
Currently, OWL does not support lists of buffers or lists of textures. Users instead must extract device pointers from OWLBuffers on a device by device basis, uploading these pointers to an OWLBuffer that's device-specific.

This usually results in applications sacrificing multi-GPU during prototyping, and it can quickly become too difficult to maintain multi-GPU compatibility long term. However, these lists of buffers and lists of texture handles are _really_ important, eg for scenes with emissive triangles and/or textures accessed outside the closest hit.

At the same time, arbitrary buffers of pointers complicate matters under the hood for OWL. Buffers of buffer pointers might result in some pointers in that buffer to themselves point to buffers of pointers. Yuck!

Instead, I'd propose we add support for 1D groups of buffer pointers and groups of textures. These groups would act like flattened lists, with no possible multi-dimensional indirection. This way, OWL could under the hood create N flattened item lists, one per device, each flattened list containing only items allocated on the corresponding device.

If we could get that working, then it would be much easier to for OWL end users to maintain multiGPU compatibility. Later down the line, OWLBufferGroups and OWLTextureGroups could additionally contain hints about NVLink stuff.

**Comment by ingowald** [comment]
Agree that would be useful, but would argue that's not a "group" - at least right now, "groups" are very explicitly groups of things that can eb traversed/intersected with a ray, with a one-to-one mapping of a group to a optixtraversable.... and for textures or buffers that doesn't make sense.

the way that worked in optix 6 (and which is probably the easeiset/best route to reach that) is that there was a device-side registry of buffers, textures, etc, then the program would create buffers of IDs, and some device-side magic would resolve a buffer-id or texture-id back to the actual buffer/texture object (using said registery). Alternatively, the way this is handled in ospray (where 'buffers' are 'data objects') is that the API transparently replaced/remaps those things, but that has its own issues. 

Buffers of IDs (with a means of looking up on the device) is how it was done in optix 6, so I'd argue that's how we should do it in OWL, too. Every buffer/texture/group etc already has a unique ID on the backend (in fact, even the registry at some point already existed), so that's the easiest way to do it.

**Comment by n8vm** [comment]
Names can change. “Group” was the first thing I thought of, but I’m open to alternatives too. “List” was another, or perhaps “Set”. 

I personally prefer having raw pointers GPU side, although a device side API would be handy. Raw pointers are much better than GLSL’s opaque handles, so we wouldn’t want to give that up too much. 

I worry somewhat that designing a device side API is outside of the scope of this feature request, and might make this feature more complicated than it needs to be to implement. I was just thinking of an extension to what OWLBuffer’s do right now, where per-device pointers would be directly exposed to the user.

**Comment by ingowald** [comment]
features supported in latest devel by allowing owlDeviceBufferCreate(...,OWL_TEXTURE,OWLTexture*) and owlDeviceBufferCreate(....,OWL_BUFFER,OWLBuffer*)

**Comment by ingowald** [comment]
avaiable in v0.9.0, where buffers can be built over buffer or texture types.
