### ISSUE TITLE
OWL and multiple entry points

### ISSUE THREAD

**Issue by Andy-Page3** [owl-project/owl#67]
I currently have an App written using Opitx6 and am considering moving to 7 in time.
I must admit i cant get my head around Optix7 but can understand the OWL abstraction almost.
In my App i have multiple pipelines (adopting Optix 7 speak) (multiple raygen programs or entry points Optix 6).
Can OWL support this would and do i need to have multiple contexts.

**Comment by ingowald** [comment]
Hey, Andy,

Multiple Entry Points should indeed work quite easily.
 
We do indeed have to be very careful with terminology here, beause I think _my_ usage of the term "pipeline" is yet different from yours :-) .... but that said, if what I _think_ you're asking for is indeed what you want - namely, having multiple different raygen programs at the same time - then yes, that is easily possible.

In "my" terminology, the pipeline is what all the programs get compiled together into, and in that terminology OWL currently supports only _one_ pipeline in a context.... but you can absolutely have different "raygens" (which _are_ the entry points!), and you can even have multiple of those in the same context (even running asynchronously at the same time, with different launch params, etc, if you so want).  I do in fact use that all the time; eg, I have a photon mapper where one raygen generates the photons, and another traces the paths that query them - easy.

If you do run into issues, also feel free to send me an email (though the github issue is also good because others can see it, too - your choice :-) ).

**Comment by Andy-Page3** [comment]
Ingo,Thanks for your prompt response. I will give it a go; I will need to put all raygen programs into a single cu file and pass this as compiled string to create module ?I am not sure how you would have different launch parameters as you would have a second statement and they would contest for the same memory (if only conceptually) ?!
  /*! launch parameters in constant memory, filled in by optix upon optixLaunch (this gets filled in from the buffer we pass to optixLaunch) */  extern "C" __constant__ LaunchParams launchParams;
  //Would you have a second statement like  extern "C" __constant__ LaunchParams2 launchParams2

Sent from Yahoo Mail on Android 
 
  On Tue, 3 Nov 2020 at 18:11, Ingo Wald<notifications@github.com> wrote:   


Hey, Andy,

Multiple Entry Points should indeed work quite easily.

We do indeed have to be very careful with terminology here, beause I think my usage of the term "pipeline" is yet different from yours :-) .... but that said, if what I think you're asking for is indeed what you want - namely, having multiple different raygen programs at the same time - then yes, that is easily possible.

In "my" terminology, the pipeline is what all the programs get compiled together into, and in that terminology OWL currently supports only one pipeline in a context.... but you can absolutely have different "raygens" (which are the entry points!), and you can even have multiple of those in the same context (even running asynchronously at the same time, with different launch params, etc, if you so want). I do in fact use that all the time; eg, I have a photon mapper where one raygen generates the photons, and another traces the paths that query them - easy.

If you do run into issues, also feel free to send me an email (though the github issue is also good because others can see it, too - your choice :-) ).

**Comment by Andy-Page3** [comment]
On the subject of Launch Parameters, 
i see a function call
owlParamsSetGroup

In advanced/optix7course/SampleRenderer.cpp called from buildAcel.Firstly i cant see this function being supplied by the owl source.Secondly why is there a separate setting of the Launch Parameters on the geom and not relying on the optix launch stage. 

    On Wednesday, 4 November 2020, 09:31:24 GMT, andy page <bagey2002@yahoo.co.uk> wrote:  
 
 Ingo,Thanks for your prompt response. I will give it a go; I will need to put all raygen programs into a single cu file and pass this as compiled string to create module ?I am not sure how you would have different launch parameters as you would have a second statement and they would contest for the same memory (if only conceptually) ?!
  /*! launch parameters in constant memory, filled in by optix upon optixLaunch (this gets filled in from the buffer we pass to optixLaunch) */  extern "C" __constant__ LaunchParams launchParams;
  //Would you have a second statement like  extern "C" __constant__ LaunchParams2 launchParams2

Sent from Yahoo Mail on Android 
 
  On Tue, 3 Nov 2020 at 18:11, Ingo Wald<notifications@github.com> wrote:   


Hey, Andy,

Multiple Entry Points should indeed work quite easily.

We do indeed have to be very careful with terminology here, beause I think my usage of the term "pipeline" is yet different from yours :-) .... but that said, if what I think you're asking for is indeed what you want - namely, having multiple different raygen programs at the same time - then yes, that is easily possible.

In "my" terminology, the pipeline is what all the programs get compiled together into, and in that terminology OWL currently supports only one pipeline in a context.... but you can absolutely have different "raygens" (which are the entry points!), and you can even have multiple of those in the same context (even running asynchronously at the same time, with different launch params, etc, if you so want). I do in fact use that all the time; eg, I have a photon mapper where one raygen generates the photons, and another traces the paths that query them - easy.

If you do run into issues, also feel free to send me an email (though the github issue is also good because others can see it, too - your choice :-) ).

**Comment by ingowald** [comment]
I'll write a wiki-article on how to use launch params a bit later today; i assume others will have the same questions .... because yes, it's not entirely obvious how that entire concept of launch parameters works - OWL IMHO makes it a bit easier to use than in optix native; but unless you understand the key concept it can indeed be confusing. 

The main confusion you're probably having (I assume so because that was _my_ initial source of confusion) is that in your mind you're probably thinking of this as if it was a host-side program, and are imagining the different raygens as different "functions" in the same "program", and the launch params as "global constant variables" in that program ... and in that case, thinking of the "same" global constants having different values for different functions in the same (host) program does indeed not make sense.

That is, however, not how this works: Maybe an easier way to think of that is to imagine each raygen program as a separate CUDA kernel (that has access to all other programs, buffers, etc), and the launch params as region of constant memory that belongs to the _launch_ of that raygen program you're executing - so different _launches_ of the same program can indeed have different values of these values (even if the rest of the GPU memory - ie, buffers, textures, acceleration structures, shader binding table, etc - are all shared between those launches). 

In the easiest way, you could set the launch params to one value, then execute a launch, set to another value, do another launch, etc (it doesn't matter whether the first and the second launch are the same raygen program or not). If you want to go crazy you can even have multiple different launches running _asynchronously_ (with different values for their launch params!)... 

As to how to do it: yes, the easiest way is probably a single .cu file (though you don't have to, you can have multiple .cu files no problem, just load each one into a different module); then set, before each launch, the members of the launch params that the respective launch requires. 

Eg, here a (very) pseudo-code-ey sample of my previous example of a photon mappper, that has separate "generatePhotons" and "renderFrame" raygens. Say, you create a file photonmapper.cu, and create a launch params like this:

struct MyLaunchParams {
   struct { 
      Photon *photons
   } commonToBothLaunches;
   struct {
       LightSource *lightSource;
       int numLghtSources;
   } onlyForPhotonGen;
   struct {
      float4 *frameBuffer;
   } onlyForRender;
};
...
and declare that as
__constant__ MyLaunchParams optixLaunchParams;

and have two diferent raygens:
OPTIX_RAYGEN_PROGRAM(tracePhotons)() { .... optixLaunchParams.onlyForPhotonGen .... };
OPTIX_RAYGEN_PROGRAM(renderFrame() { ... optixLauchParams.frameBuffer[i] = ... };

Then on the host side you can create the two raygens

OWLRayGen rgTracePhotons = owlRayGenCreate(....);
OWLRayGen rgRenderFrame = owlRayGenCreate(....);

and a launch params as
OWLVarDecl lpVars[] = { .... all member declarations, see sample codes ... };
OWLParams lp = owlParamsCreate(......);

then you could launch those two - with different values for the 'otpixLauchParams' but otherwise fully shared context including accel structs, SBT, etc) as follows:

owlParamsSet1i(lp,"onlyForPhotonGen.numLights",numLights);
...
owlLaunch2D(rgTracePhotons, ......, lp);
...
owlParamsSetBuffer(lp,"onlyForTrace.frameBuffer",fb);
...
owlLaunch2D(rgRenderFrame, ..... lp);

**Comment by Andy-Page3** [comment]
Yes In my app it would make more sense to create multiple modules one for each raygen / entry point.This would also allow me to keep the current layout of cu files and would make sense in terms of all using consistenly named launch parameters.
    On Wednesday, 4 November 2020, 16:46:25 GMT, Ingo Wald <notifications@github.com> wrote:  
 
 


I'll write a wiki-article on how to use launch params a bit later today; i assume others will have the same questions .... because yes, it's not entirely obvious how that entire concept of launch parameters works - OWL IMHO makes it a bit easier to use than in optix native; but unless you understand the key concept it can indeed be confusing.

The main confusion you're probably having (I assume so because that was my initial source of confusion) is that in your mind you're probably thinking of this as if it was a host-side program, and are imagining the different raygens as different "functions" in the same "program", and the launch params as "global constant variables" in that program ... and in that case, thinking of the "same" global constants having different values for different functions in the same (host) program does indeed not make sense.

That is, however, not how this works: Maybe an easier way to think of that is to imagine each raygen program as a separate CUDA kernel (that has access to all other programs, buffers, etc), and the launch params as region of constant memory that belongs to the launch of that raygen program you're executing - so different launches of the same program can indeed have different values of these values (even if the rest of the GPU memory - ie, buffers, textures, acceleration structures, shader binding table, etc - are all shared between those launches).

In the easiest way, you could set the launch params to one value, then execute a launch, set to another value, do another launch, etc (it doesn't matter whether the first and the second launch are the same raygen program or not). If you want to go crazy you can even have multiple different launches running asynchronously (with different values for their launch params!)...

As to how to do it: yes, the easiest way is probably a single .cu file (though you don't have to, you can have multiple .cu files no problem, just load each one into a different module); then set, before each launch, the members of the launch params that the respective launch requires.

Eg, here a (very) pseudo-code-ey sample of my previous example of a photon mappper, that has separate "generatePhotons" and "renderFrame" raygens. Say, you create a file photonmapper.cu, and create a launch params like this:

struct MyLaunchParams {
struct {
Photon *photons
} commonToBothLaunches;
struct {
LightSource *lightSource;
int numLghtSources;
} onlyForPhotonGen;
struct {
float4 *frameBuffer;
} onlyForRender;
};
...
and declare that as
constant MyLaunchParams optixLaunchParams;

and have two diferent raygens:
OPTIX_RAYGEN_PROGRAM(tracePhotons)() { .... optixLaunchParams.onlyForPhotonGen .... };
OPTIX_RAYGEN_PROGRAM(renderFrame() { ... optixLauchParams.frameBuffer[i] = ... };

Then on the host side you can create the two raygens

OWLRayGen rgTracePhotons = owlRayGenCreate(....);
OWLRayGen rgRenderFrame = owlRayGenCreate(....);

and a launch params as
OWLVarDecl lpVars[] = { .... all member declarations, see sample codes ... };
OWLParams lp = owlParamsCreate(......);

then you could launch those two - with different values for the 'otpixLauchParams' but otherwise fully shared context including accel structs, SBT, etc) as follows:

owlParamsSet1i(lp,"onlyForPhotonGen.numLights",numLights);
...
owlLaunch2D(rgTracePhotons, ......, lp);
...
owlParamsSetBuffer(lp,"onlyForTrace.frameBuffer",fb);
...
owlLaunch2D(rgRenderFrame, ..... lp);

**Comment by ingowald** [comment]
Yes, you can definitely have different .cu files within the same context (eg, one raygen in one, and another in another). You _can_ even use different types for the "optixLaunchParams" in both cu files, but that can easily lead to funny results if you have functions other than your raygen programs - say, some CH or AH program - that also use those, and that get used by both raygens (say, if both raygens programs shoot rays, and thus end up calling the same CH program). 

Instead, I'd strongly suggest to declare the launch params struct type in a shared header file, in the same way i described abvoe (ie, one sub-struct per type of raygen you want to use - simply ignore thoes variables your raygen doesn't use)... just to make sure you're not getting any weird results.

Note the launch params in owl always _have_ to be called "optixLaunchParams" - the name of that struct is actually baked into the context, so cannot be changed. You can assign different values per launch, but you can't change the name..

**Comment by ingowald** [comment]
I just put a very detailed page up on the wiki, which describes both variables and launch params. Probably too detailed for the casual user.... but should have all the details I could think of.

**Comment by Andy-Page3** [comment]
Thanks I have already started reading it.

Sent from Yahoo Mail on Android 
 
  On Wed, 4 Nov 2020 at 20:16, Ingo Wald<notifications@github.com> wrote:   


I just put a very detailed page up on the wiki, which describes both variables and launch params. Probably too detailed for the casual user.... but should have all the details I could think of.

**Comment by ingowald** [comment]
Only just seen the following part of your question:
> In advanced/optix7course/SampleRenderer.cpp called from buildAcel.Firstly i cant see this function being supplied by the owl 
> source.

The reason you can't easily find these "owl<Type>Set<abb>() functions with a search is that I constructed all the NxM possibel variablts using a few macros, in include/owl_host.h (look for OWL_SET_HELPERS). These functions internally map to owl<Type>GetVariable (eg., owlParamGetVariable("name") gets handle to varaible with given name for a launch param object), folowed by owlVariableSet<type>(...) - so the DLL actually only contains the GetVariable's and VariableSet's, the other helpers are currently defined as inline (and constructed through macros) in the header file. I just opened an issue though, to add tehm all explicitly - it's certainly easier to document and read this way.

> Secondly why is there a separate setting of the Launch Parameters on the geom and not relying on the optix launch stage. 
This one I'm confused about - launch params should never be set on a geom. Geoms go into the shader binding table, launch params go into the "__constant__ ... optixLaunchParams". What I _suspect_ is that you're reading the order of who gets assigned to whom backwards: ie, owlParamsSetGeom would mean that a geom gets assigned to a param, not the other way around (I basically follow the C++ ordering here: owlParamsSetGeom is the equivalent of OWLParams::setGeom(), as I would write it in C++)

**Comment by Andy-Page3** [comment]
Yes sorry you are exactly right i am reading it backwards !
I notice one more thing in Optix 6 a miss program is linked to a ray type.When yiou create a Miss program (owlMissProgCreate) yiu are not taking a ray type as an arg. Is the ray type id inferred by the creation order.
    On Thursday, 5 November 2020, 17:49:28 GMT, Ingo Wald <notifications@github.com> wrote:  
 
 


Only just seen the following part of your question:


In advanced/optix7course/SampleRenderer.cpp called from buildAcel.Firstly i cant see this function being supplied by the owl
source.


The reason you can't easily find these "owlSet() functions with a search is that I constructed all the NxM possibel variablts using a few macros, in include/owl_host.h (look for OWL_SET_HELPERS). These functions internally map to owlGetVariable (eg., owlParamGetVariable("name") gets handle to varaible with given name for a launch param object), folowed by owlVariableSet(...) - so the DLL actually only contains the GetVariable's and VariableSet's, the other helpers are currently defined as inline (and constructed through macros) in the header file. I just opened an issue though, to add tehm all explicitly - it's certainly easier to document and read this way.


Secondly why is there a separate setting of the Launch Parameters on the geom and not relying on the optix launch stage.
This one I'm confused about - launch params should never be set on a geom. Geoms go into the shader binding table, launch params go into the "constant ... optixLaunchParams". What I suspect is that you're reading the order of who gets assigned to whom backwards: ie, owlParamsSetGeom would mean that a geom gets assigned to a param, not the other way around (I basically follow the C++ ordering here: owlParamsSetGeom is the equivalent of OWLParams::setGeom(), as I would write it in C++)

**Comment by ingowald** [comment]
Re miss progs: have a look at "owlMissProgSet()".
Initially they were indeed inferred from order (and by default, still are: if you create two they will automatically be used for type 0 and 1, respecitvely, unless you call MissProgSet) .... but somebody else pointed out before that that was too restrictive. So you _can_ use the implicit order in which you generate them, or you can call owlMissProgSet to assign them explicitly, too.

**Comment by ingowald** [comment]
added documentatoin to wiki; closing this.
