### ISSUE TITLE
2 bugs: Optix 7.2 and latest TBB 2021.1

### ISSUE THREAD

**Issue by oscarbg** [owl-project/owl#68]
Hi,
two bugs using latest TBB 2021.1 and Optix 7.2..

*first: FindTBB.cmake doesn't work with TBB 2021.1 from Oneapi beta 10:
as tbb_stddef.h doesn't exist and version is in version.h

change:
FILE(READ ${TBB_INCLUDE_DIR}/tbb/tbb_stddef.h TBB_STDDEF_H) 
to
FILE(READ ${TBB_INCLUDE_DIR}/tbb/version.h TBB_STDDEF_H) 

*second: code with Optix 7.2 SDK doesn't compile:
FIX:
InstanceGroup.cpp:
comment:
/* instanceInput.instanceArray.aabbs
      = dd.motionAABBsBuffer.d_pointer;
    instanceInput.instanceArray.numAabbs
      = (int)motionAABBs.size();*/

as Optix 7.2 removes aabbs and numAabbs fields..

**Comment by ingowald** [comment]
Thx!
Optix 7.2 I'll double-check right away - though I already used 7.2, but might not have tried latest public headers, so will double-check. Thx for reporting this; this is obviously critical.

Oneapi beta I'll have to take your word for it, i fear .... but if that change still also works with non-beta TBB versions then I'll just take it. Thx!

**Comment by ingowald** [comment]
Nice catch. Thanks again.

Re TBB: Your suggested change breaks for non-intel-beta-software, so I instead now check which of the two files exists. I'd atually argue that this is a intel openapi/TBB bug, but this should be a workaround that works with both. I can't test that change, though (I don't have oneapi beta installed), so please let me know if the latest push does not work.

Re Optix 7.2. Fixed. Your suggested change would have broken 7.1 (which still needs these fields), but I'm now checking version, and setting (and computing....) those only for 7.1. Nice catch indeed. Turns out testing with a new SDK version is much more effective if you also change your cmake paths to actually use any newly installed headers :-/

Latest version i just pushed (master, v1.0.4) should have both fixed. Again - thx, and let me know if they don't completely fix this.
