### ISSUE TITLE
example contains an error it seems

### ISSUE THREAD

**Issue by DenisRiedijk** [owl-project/owl#81]
Just discovered this seemingly very useful wrapper around optix7 and checking out the documentation I noticed the following:

Several locations show the simple example of uploading triangle mesh and building an sbt. When declaring the index buffer it appears that index buffer is declared as a float3 (OWL_FLOAT3) instead of uint3.

   OWLBuffer idxBuffer
      = owlDeviceBufferCreate(ctx,OWL_FLOAT3,
	                          idx.size(),idx.data());

**Comment by ingowald** [comment]
Outch. Thanks for reporting. My suspicion is that this'll work just fine in practice, since the buffer class will use that specified type only to compute the size of the elements, and will not do any type conversions. Ie, if the sample actually creates this buffer with an initializer array that contains float3s it'll just copy those float3s in, and use exaclty those float3s (as float3s) on the device, even though the buffer "thinks" it was int3s :-/

Still - even though it does work this way it's of course not the intended way it should be used, so : "good catch".

**Comment by ingowald** [comment]
Found (and fixed) two instances of that: once in sierpinski sample, and once in readme. If you see any more, please let me know.
Thanks for reporting!

**Comment by DenisRiedijk** [comment]
Glad to be able to be of use for OSS.

I did in the end actually not use owl and am using Optix7 directly (in a
matlab MEX file).
But when trying to figure out what I was doing wrong I discovered your blog
post about OWL, so I was very tempted to try it out, but getting things to
work in a MEX file is challenging, especially with std::cout not working.
Also the fact I was trying to figure out what I was doing wrong (something
completely not optix-specific of course) led me to notice the difference in
float3 vs int3.

Kind regards,
Dènis
