### ISSUE TITLE
What's involved in adding support for >= Optix 7.1 curves?

### ISSUE THREAD

**Issue by erichocean** [owl-project/owl#85]
I'm happy to take a stab at adding support, but I'm using OWL precisely because my native Optix 7 skills are currently at n00b levels.

Any pointers on what an acceptable pull request would look like? Maybe a hasty design document someone has written up already?

**Comment by ingowald** [comment]
Re design documents: no, we dont' have those. Only ask I'd have it to make any PRs relative to devel, not master, as master is supposed to always be reasonably tested before pushing, so accepting completely new PRs into is always a bit iffy. In fact I'd suggest to first do that in a branch, so different people can jump in if required.

As to how to add: OWL currently mirrors the OptiX design context as closely as possible in that what's a different acceleration structure will also be a different accel struct in OWL, etc. in OWL we expose that as geometry "kinds", where each kind is something that cannot be mixed into the same accel with geometries of other kinds. Ie, there's a OWL_GEOM_USER and OWL_GEOM_TRIANGLES because those need to be in different groups/accels. Curves are a different kind, so there shoule be a new OWL_GEOM_CURVES. (funnily I see there's already a OWL_GEOM_HAIR defined, just not implemented ....).

The same then goes for groups: there's owlTrianglesGeomGroupCreate and owlUserGeomGroupCreate for triangles and user geoms, so there would also have to be a owlCurvesGeomGroupCreate or something like that. And just like there's a owlTrianglesSetVertices and owlTrianglesSetIndices there'd have to be similar functions for owlCurvesSet<WhatEverNeedsSetting>(). After that, it should be mostly copy and paste from the exsting triangle geom (owl/Triangles.cu) and triangle geom group (owl/TrianglesGeomGroup.cpp) into respective Curves.cu etc.

How to set the buid inputs for curves can be cross-checked (ie, copy-n-pasted) from the native optix curves sample.

And of course, it'd be great to have a mini-sample for testing.

**Comment by ingowald** [comment]
If you do start to take a stab at that pls send me an email; then i'll invite you into my personal slackspace for any discussions/questions re that (<myusername>@gmail.com). I'd love to see that happen, so happy to help where i can.

**Comment by ingowald** [comment]
got a frist branch that supports curves as a new geometry type; supporting all degrees (1-3) and both with and without caps.

**Comment by ingowald** [comment]
Merged in iw/curves branch, so should now have support for optix curves as well. Note there are _not_ yet any samples for that, so this functionality is minimally tested.
